{{-- resources/views/components/provisioning-table.blade.php --}}
<div class="card border-0 shadow-sm">
    <div class="card-header bg-white border-0 py-3">
        <div class="d-flex justify-content-between align-items-center">
            <h5 class="card-title mb-0 text-primary">
                <i class="fas fa-table me-2"></i>
                Provisioning Data
            </h5>
            <div class="table-controls d-flex align-items-center">
                <label for="perPage" class="form-label me-2 mb-0 text-muted">Show:</label>
                <select class="form-select form-select-sm" id="perPage" style="width: auto;">
                    <option value="10">10</option>
                    <option value="20" selected>20</option>
                    <option value="30">30</option>
                    <option value="40">40</option>
                </select>
                <span class="text-muted ms-2">entries</span>
            </div>
        </div>
    </div>
    
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-hover mb-0" id="provisioningTable">
                <thead class="table-primary">
                    <tr>
                        <th scope="col">
                            Property Name
                        </th>
                        <th scope="col">
                            Property Type
                        </th>
                        <th scope="col">
                            Property Address
                        </th>
                        <th scope="col">
                            System Type
                        </th>
                        <th scope="col">
                            PfSense IP
                        </th>
                    </tr>
                </thead>
                <tbody id="tableBody">
                    {{-- Data will be loaded via API --}}
                    <tr id="loadingRow">
                        <td colspan="5" class="text-center py-4">
                            <div class="spinner-border text-primary" role="status">
                                <span class="visually-hidden">Loading...</span>
                            </div>
                            <div class="mt-2">Loading network management data...</div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    
    <div class="card-footer bg-white border-0 py-3">
        <div class="d-flex justify-content-between align-items-center flex-wrap">
            <div class="table-info">
                <span class="text-muted">
                    Showing <span id="showingStart">1</span> to <span id="showingEnd">20</span> of <span id="totalEntries">20</span> entries
                </span>
            </div>
            
            <nav aria-label="Table pagination">
                <ul class="pagination pagination-sm mb-0" id="pagination">
                    {{-- Pagination will be dynamically generated by JavaScript --}}
                </ul>
            </nav>
        </div>
    </div>
</div>

<style>
.table-responsive {
    border-radius: 0;
}

.table th {
    background-color: #13395d;
    color: white;
    font-weight: 600;
    border: none;
    padding: 15px 12px;
    vertical-align: middle;
}

.table td {
    padding: 12px;
    vertical-align: middle;
    border-bottom: 1px solid #e9ecef;
}

.table-row {
    /* No animations or hover effects */
}

.clickable-row:hover {
    background-color: #f8f9fa;
    transition: background-color 0.2s ease;
}

.badge {
    font-size: 0.75rem;
    padding: 0.35rem 0.65rem;
    border-radius: 6px;
    font-weight: 500;
}

.pagination .page-link {
    border: 1px solid #e9ecef;
    color: #667eea;
    padding: 0.5rem 0.75rem;
    margin: 0 2px;
    border-radius: 6px;
    transition: all 0.3s ease;
}

.pagination .page-link:hover {
    background-color: #667eea;
    border-color: #667eea;
    color: white;
    transform: translateY(-1px);
}

.pagination .page-item.active .page-link {
    background-color: #13395d;
    border-color: #667eea;
    color: white;
    box-shadow: 0 2px 8px rgba(102, 126, 234, 0.3);
}

.pagination .page-item.disabled .page-link {
    color: #6c757d;
    background-color: #f8f9fa;
    border-color: #e9ecef;
}

.form-select:focus {
    border-color: #667eea;
    box-shadow: 0 0 0 0.2rem rgba(102, 126, 234, 0.25);
}

.card {
    border-radius: 12px;
    overflow: hidden;
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
}

code {
    background-color: #f8f9fa;
    padding: 0.25rem 0.5rem;
    border-radius: 0.25rem;
    font-family: 'Courier New', monospace;
    font-size: 0.9rem;
}

@media (max-width: 768px) {
    .table-responsive {
        font-size: 0.875rem;
    }
    
    .table th, .table td {
        padding: 8px;
    }
    
    .d-flex.justify-content-between {
        flex-direction: column;
        gap: 1rem;
    }
    
    .table-info {
        order: 2;
        text-align: center;
    }
    
    .pagination {
        order: 1;
        justify-content: center;
    }
}

/* Spinner animation used as a fallback if GIF fails to load */
@keyframes spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
}
</style>

<script>
// Function to subtract 1 from an IP address
function subtractOneFromIP(ip) {
    if (!ip || typeof ip !== 'string') {
        return ip || '';
    }
    
    // Validate IP format
    const ipRegex = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/;
    const match = ip.match(ipRegex);
    
    if (!match) {
        return ip; // Return original if not a valid IP
    }
    
    // Convert IP to long integer
    const parts = match.slice(1, 5).map(Number);
    
    // Validate each part is between 0-255
    if (parts.some(part => part < 0 || part > 255)) {
        return ip; // Return original if invalid
    }
    
    // Convert to long integer
    let long = (parts[0] << 24) + (parts[1] << 16) + (parts[2] << 8) + parts[3];
    
    // Subtract 1
    long -= 1;
    
    // Convert back to IP
    const newParts = [
        (long >>> 24) & 0xFF,
        (long >>> 16) & 0xFF,
        (long >>> 8) & 0xFF,
        long & 0xFF
    ];
    
    return newParts.join('.');
}

document.addEventListener('DOMContentLoaded', function() {
    const perPageSelect = document.getElementById('perPage');
    const tableBody = document.getElementById('tableBody');
    const showingStart = document.getElementById('showingStart');
    const showingEnd = document.getElementById('showingEnd');
    const totalEntries = document.getElementById('totalEntries');
    const pagination = document.getElementById('pagination');
    
    let currentPage = 1;
    let rowsPerPage = parseInt(perPageSelect.value) || 20;
    let allRowsData = [];
    let totalRows = 0;
    
    // Helper: show transition overlay and navigate (mirrors create.blade behavior)
    function navigateWithOverlay(url) {
        try {
            const overlay = document.createElement('div');
            overlay.id = 'transition-overlay';
            overlay.style.cssText = `
                position: fixed;
                top: 70px; /* Height of topbar */
                left: 240px; /* Width of sidebar */
                right: 0;
                bottom: 0;
                background-color: rgba(255, 255, 255, 0.98);
                backdrop-filter: blur(8px);
                z-index: 9999;
                display: flex;
                align-items: center;
                justify-content: center;
                transition: opacity 0.3s ease;
                opacity: 0;
            `;

            // Responsive offsets
            if (window.innerWidth <= 992) {
                overlay.style.left = '0px';
                overlay.style.top = '60px';
            }

            // Loading container
            const loadingContainer = document.createElement('div');
            loadingContainer.style.cssText = `
                text-align: center;
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
                padding: 2rem;
            `;

            // GIF element
            const gifElement = document.createElement('img');
            gifElement.src = '/assets/images/Transition_Animation.gif';
            gifElement.alt = 'Loading...';
            gifElement.style.cssText = `
                max-width: 300px;
                max-height: 300px;
                width: auto;
                height: auto;
                margin-bottom: 1.5rem;
            `;

            // Spinner fallback
            const spinner = document.createElement('div');
            spinner.style.cssText = `
                width: 60px;
                height: 60px;
                border: 6px solid #e5e7eb;
                border-top: 6px solid #3b82f6;
                border-radius: 50%;
                animation: spin 1s linear infinite;
                margin: 0 auto 1.5rem;
                display: none;
            `;

            // Add CSS keyframes if not present
            if (!document.querySelector('#loading-spinner-style')) {
                const style = document.createElement('style');
                style.id = 'loading-spinner-style';
                style.textContent = `
                    @keyframes spin { 0% { transform: rotate(0deg);} 100% { transform: rotate(360deg);} }
                `;
                document.head.appendChild(style);
            }

            let proceeded = false;
            const proceed = () => {
                if (proceeded) return;
                proceeded = true;
                try { sessionStorage.setItem('showTransitionOverlay', '1'); } catch (_) {}
                window.location.href = url;
            };

            gifElement.addEventListener('load', () => {
                // Show the overlay for a short, visible duration (like create flow)
                setTimeout(proceed, 3000);
            });

            gifElement.addEventListener('error', () => {
                gifElement.style.display = 'none';
                spinner.style.display = 'block';
                setTimeout(proceed, 1500);
            });

            // Assemble DOM
            loadingContainer.appendChild(gifElement);
            loadingContainer.appendChild(spinner);
            overlay.appendChild(loadingContainer);
            document.body.appendChild(overlay);

            // Fade in, and timeout fallback
            requestAnimationFrame(() => {
                overlay.style.opacity = '1';
            });

            const handleResize = () => {
                if (window.innerWidth <= 992) {
                    overlay.style.left = '0px';
                    overlay.style.top = '60px';
                } else {
                    overlay.style.left = '240px';
                    overlay.style.top = '70px';
                }
            };
            window.addEventListener('resize', handleResize);

            // Max timeout safeguard
            setTimeout(proceed, 8000);
        } catch (e) {
            window.location.href = url;
        }
    }

    // Initialize by fetching data from API
    fetchNetworkManagementData();
    
    // Handle rows per page change
    perPageSelect.addEventListener('change', function() {
        rowsPerPage = parseInt(this.value);
        currentPage = 1;
        updateTable();
    });

    // Function to fetch data from API
    async function fetchNetworkManagementData() {
        try {
            // Show loading state
            tableBody.innerHTML = `
                <tr id="loadingRow">
                    <td colspan="5" class="text-center py-4">
                        <div class="spinner-border text-primary" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                        <div class="mt-2">Loading network management data...</div>
                    </td>
                </tr>
            `;

            // Get CSRF token
            const token = document.querySelector('meta[name="csrf-token"]')?.getAttribute('content');
            
            const response = await fetch('/api/network-management', {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-TOKEN': token,
                    'Accept': 'application/json',
                    'X-Requested-With': 'XMLHttpRequest'
                },
                credentials: 'same-origin'
            });

            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }

            const result = await response.json();
            
            if (result.success) {
                // Transform API data to table format with ID for navigation
                originalData = result.data.map(item => [
                    String(item.property_name || ''),
                    String(item.property_type || ''),
                    String(item.property_address || ''),
                    String(item.system_type || ''),
                    String(item.first_usable_ip || ''),
                    item.id // Store ID for navigation (keep as number for navigation)
                ]);
                allRowsData = [...originalData]; // Copy for current display
                totalRows = allRowsData.length;
                
                // Update table with fetched data
                updateTable();
            } else {
                showError('Failed to load data: ' + (result.message || 'Unknown error'));
            }
        } catch (error) {
            console.error('Error fetching network management data:', error);
            showError('Failed to load network management data. Please try again.');
        }
    }

    // Function to show error state
    function showError(message) {
        tableBody.innerHTML = `
            <tr>
                <td colspan="5" class="text-center py-4 text-danger">
                    <i class="fas fa-exclamation-triangle mb-2"></i>
                    <div>${message}</div>
                    <button class="btn btn-sm btn-outline-primary mt-2" onclick="location.reload()">Retry</button>
                </td>
            </tr>
        `;
        
        // Reset pagination info
        showingStart.textContent = '0';
        showingEnd.textContent = '0';
        totalEntries.textContent = '0';
        pagination.innerHTML = '';
    }

    // Search functionality
    let originalData = [];
    let filteredData = [];
    let isFiltered = false;

    // Expose search functions globally for the search page
    window.filterProvisioningTable = function(query) {
        if (!query || query.trim() === '') {
            resetProvisioningTableFilter();
            return;
        }

        const searchQuery = query.toLowerCase();
        filteredData = originalData.filter(row => {
            // Search only the first 5 columns (excluding the ID column at index 5)
            return row.slice(0, 5).some(cell => 
                cell && typeof cell === 'string' && cell.toLowerCase().includes(searchQuery)
            );
        });

        isFiltered = true;
        allRowsData = filteredData;
        totalRows = filteredData.length;
        currentPage = 1;
        updateTable();
    };

    window.resetProvisioningTableFilter = function() {
        isFiltered = false;
        allRowsData = originalData;
        totalRows = originalData.length;
        currentPage = 1;
        updateTable();
    };
    
    function updateTable() {
        // Clear current table
        tableBody.innerHTML = '';
        
        // Handle empty data case
        if (totalRows === 0) {
            const emptyMessage = isFiltered ? 'No results found for your search.' : 'No data available.';
            tableBody.innerHTML = `
                <tr>
                    <td colspan="5" class="text-center py-4 text-muted">
                        <i class="fas fa-search mb-2"></i>
                        <div>${emptyMessage}</div>
                    </td>
                </tr>
            `;
            
            // Reset pagination info
            showingStart.textContent = '0';
            showingEnd.textContent = '0';
            totalEntries.textContent = '0';
            pagination.innerHTML = '';
            return;
        }
        
        // Calculate pagination
        const startIndex = (currentPage - 1) * rowsPerPage;
        const endIndex = Math.min(startIndex + rowsPerPage, totalRows);
        const visibleRowsData = allRowsData.slice(startIndex, endIndex);
        
        // Add visible rows to table
        visibleRowsData.forEach(rowData => {
            // Create new row element with data
            const row = document.createElement('tr');
            row.className = 'table-row clickable-row';
            row.style.cursor = 'pointer';
            row.innerHTML = `
                <td>${rowData[0]}</td>
                <td>${rowData[1]}</td>
                <td>${rowData[2]}</td>
                <td>${rowData[3]}</td>
                <td><code class="text-muted">${subtractOneFromIP(rowData[4])}</code></td>
            `;
            
            // Add click event listener for navigation with transition overlay
            row.addEventListener('click', function() {
                const id = rowData[5]; // ID is stored in the 6th position (index 5)
                if (id) {
                    navigateWithOverlay(`/network-provisioning/details/${id}`);
                }
            });
            
            tableBody.appendChild(row);
        });
        
        // Update showing info
        showingStart.textContent = totalRows > 0 ? startIndex + 1 : 0;
        showingEnd.textContent = endIndex;
        totalEntries.textContent = totalRows;
        
        // Update pagination
        updatePagination();
    }
    
    function updatePagination() {
        const totalPages = Math.ceil(totalRows / rowsPerPage);
        pagination.innerHTML = '';
        
        // Don't show pagination if there's only one page or no data
        if (totalPages <= 1) {
            return;
        }
        
        // Previous button
        const prevBtn = createPageItem('prev', '<i class="fas fa-chevron-left"></i>');
        prevBtn.classList.toggle('disabled', currentPage === 1);
        pagination.appendChild(prevBtn);
        
        // Page numbers
        const startPage = Math.max(1, currentPage - 2);
        const endPage = Math.min(totalPages, currentPage + 2);
        
        if (startPage > 1) {
            pagination.appendChild(createPageItem(1, '1'));
            if (startPage > 2) {
                const ellipsis = document.createElement('li');
                ellipsis.className = 'page-item disabled';
                ellipsis.innerHTML = '<span class="page-link">...</span>';
                pagination.appendChild(ellipsis);
            }
        }
        
        for (let i = startPage; i <= endPage; i++) {
            const pageItem = createPageItem(i, i.toString());
            pageItem.classList.toggle('active', i === currentPage);
            pagination.appendChild(pageItem);
        }
        
        if (endPage < totalPages) {
            if (endPage < totalPages - 1) {
                const ellipsis = document.createElement('li');
                ellipsis.className = 'page-item disabled';
                ellipsis.innerHTML = '<span class="page-link">...</span>';
                pagination.appendChild(ellipsis);
            }
            pagination.appendChild(createPageItem(totalPages, totalPages.toString()));
        }
        
        // Next button
        const nextBtn = createPageItem('next', '<i class="fas fa-chevron-right"></i>');
        nextBtn.classList.toggle('disabled', currentPage === totalPages);
        pagination.appendChild(nextBtn);
    }
    
    function createPageItem(page, text) {
        const li = document.createElement('li');
        li.className = 'page-item';
        
        const a = document.createElement('a');
        a.className = 'page-link';
        a.href = 'javascript:void(0);';
        a.innerHTML = text;
        a.style.cursor = 'pointer';
        
        a.addEventListener('click', function(e) {
            e.preventDefault();
            e.stopPropagation();
            
            if (li.classList.contains('disabled') || li.classList.contains('active')) {
                return;
            }
            
            if (page === 'prev') {
                currentPage = Math.max(1, currentPage - 1);
            } else if (page === 'next') {
                currentPage = Math.min(Math.ceil(totalRows / rowsPerPage), currentPage + 1);
            } else {
                currentPage = page;
            }
            
            updateTable();
            return false;
        });
        
        li.appendChild(a);
        return li;
    }
});
</script>